name: ESLint

on:
  push:
    branches: '**'
  pull_request:

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ESLint
        run: npm install -g eslint@^8.23.1

      - name: Run Web ESLint
        working-directory: ./packages/web
        run: |
          npm install eslint-plugin-react@latest --save-dev
          npm run lint
        continue-on-error: false
      
      - name: Run API ESLint
        working-directory: ./packages/api
        run: |
          npm install eslint-plugin-react@latest --save-dev
          npm run lint
        continue-on-error: false
